# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180111_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
        ),
    ]
