# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cliente_nome'),
        ('app', '0007_pedido_observacoes'),
    ]

    operations = [
    ]
