# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
