# Generated by Django 3.2.16 on 2023-01-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20180223_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
    ]
