# Generated by Django 3.2.16 on 2023-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_formapagamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.TextField(blank=True, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.TextField(blank=True, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='complemento',
            field=models.TextField(blank=True, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
